a=int(input("Enter the value of A"))
b=int(input("Enter the value of B"))
c=int(input("Enter the value of C"))
#print(a*x**2+b*x+c)
r1=(-(b)+((b**2)-4*a*c)**1/2)/(2*a)
r2=(-(b)-((b**2)-4*a*c)**1/2)/(2*a)
print(r1)
print(r2)
